[package]
name = "nextjs_react_compiler_reactive_scopes"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = true

[dependencies]
react_compiler_ast = { workspace = true }
react_compiler_diagnostics = { workspace = true }
react_compiler_hir = { workspace = true }
indexmap = "2"
serde_json = "1"
sha2 = "0.10"
hmac = "0.12"

[lib]
name = "react_compiler_reactive_scopes"
