//! Prepares the freshly-vendored React Compiler crates for publishing. Crate naming
//! changes happen in `Cargo.toml` ONLY — source, directories, and import/lib names stay
//! exactly as upstream (`react_compiler*`); the only naming change is the published
//! `[package] name`, which becomes `nextjs_react_compiler*`. The tool also writes the
//! workspace-level `LICENSE` and `oxc_release.toml`, and drops `Cargo.lock`. Run on every
//! `just sync`; idempotent.
//!
//! Per crate (`Cargo.toml` only):
//!   - `[package] name`  -> `nextjs_react_compiler_X`  (the published name)
//!   - `[lib] name`      -> `react_compiler_X`         (kept, so `use react_compiler_X` still works)
//!   - inherits version/edition/license/description/repository from `[workspace.package]`
//!   - internal deps become `{ workspace = true }`
//!   - any `regex` dep is swapped to a `regex-lite` package rename (import name kept)
//!   - `publish` = true for `react_compiler` and its (transitive) deps; false for the rest
//! Root `[workspace.dependencies]` maps each import name to its published package:
//!   `react_compiler_X = { package = "nextjs_react_compiler_X", version, path }`
//!
//! Usage: `codemod [TREE_DIR]`   (default: `react-compiler`)

use std::collections::{BTreeSet, HashMap, VecDeque};
use std::fs;
use std::path::{Path, PathBuf};

use toml_edit::{value, DocumentMut, InlineTable, Item, Table, Value};

// The published version is passed in as the 2nd CLI arg (see `main`) rather than
// hardcoded here, so `cargo-release-oxc` stays the single source of truth and a
// resync never reverts a released version.
const EDITION: &str = "2024";
const LICENSE: &str = "MIT";
const DESCRIPTION: &str = "Rust port of the React Compiler, vendored from facebook/react.";
const REPOSITORY: &str = "https://github.com/vercel/forked-react-compiler";
/// React's MIT LICENSE, kept as a local copy (`./LICENSE`) and linked into the
/// tool so syncing needs no network for it.
const LICENSE_TEXT: &str = include_str!("../../LICENSE");
/// git-cliff config that `cargo release-oxc` loads from the workspace root.
const CLIFF_CONFIG: &str = include_str!("../cliff.toml");
/// `cargo release-oxc` (https://github.com/oxc-project/cargo-release-oxc) config.
/// Written into the vendored workspace so `cargo release-oxc publish` can run there.
/// `root_crate` is the published name of `react-compiler/crates/react_compiler`.
const RELEASE_CONFIG: &str = r#"# Configuration for `cargo release-oxc` (https://github.com/oxc-project/cargo-release-oxc).
# Regenerated by ./codemod on every `just sync`. Run from this directory, e.g.:
#   cargo release-oxc publish --release crates [--dry-run]
# (publishes `nextjs_react_compiler` + its deps; `publish = false` crates are skipped).
[[releases]]
name = "crates"
root_crate = "nextjs_react_compiler"
versioned_files = ["Cargo.toml"]
"#;

/// A workspace member crate.
struct Member {
    /// Lib/import name, kept as upstream, e.g. `react_compiler_ast`.
    import_name: String,
    /// Published package name, e.g. `nextjs_react_compiler_ast`.
    package_name: String,
    /// Path relative to the workspace root, e.g. `crates/react_compiler_ast`.
    rel_path: String,
    /// Absolute path to the crate's `Cargo.toml`.
    manifest: PathBuf,
    /// Whether the crate has a library target (`src/lib.rs`).
    has_lib: bool,
}

fn main() {
    let root = PathBuf::from(
        std::env::args()
            .nth(1)
            .unwrap_or_else(|| "react-compiler".to_string()),
    );

    // Version to stamp on `[workspace.package]` and every inter-crate dep. Passed
    // by `just sync`/`just codemod`, which read it from the current `Cargo.toml`
    // so `cargo-release-oxc` remains the only thing that bumps it.
    let version = std::env::args()
        .nth(2)
        .unwrap_or_else(|| "0.1.0".to_string());

    let members = members(&root);
    let internal: BTreeSet<&str> = members.iter().map(|m| m.import_name.as_str()).collect();
    let publish = publish_closure(&members, &internal);
    edit_root_manifest(&root, &members, &version);
    for member in &members {
        edit_member_manifest(member, &internal, publish.contains(&member.import_name));
    }

    fs::write(root.join("LICENSE"), LICENSE_TEXT).expect("write LICENSE");
    fs::write(root.join("oxc_release.toml"), RELEASE_CONFIG).expect("write oxc_release.toml");
    fs::write(root.join("cliff.toml"), CLIFF_CONFIG).expect("write cliff.toml");
    let dropped_lock = fs::remove_file(root.join("Cargo.lock")).is_ok();

    println!(
        "codemod: published name -> nextjs_react_compiler_* on {} crate(s), wrote LICENSE + oxc_release.toml + cliff.toml{}",
        members.len(),
        if dropped_lock { ", dropped Cargo.lock" } else { "" },
    );
}

/// Resolve workspace `members` (expanding a trailing `/*`) to `Member`s, sorted by import name.
fn members(root: &Path) -> Vec<Member> {
    let doc = read_doc(&root.join("Cargo.toml"));
    let entries = doc
        .get("workspace")
        .and_then(|w| w.get("members"))
        .and_then(Item::as_array);

    let mut out = Vec::new();
    let Some(entries) = entries else {
        return out;
    };
    for member in entries.iter().filter_map(|m| m.as_str()) {
        let rel_paths = match member.strip_suffix("/*") {
            Some(parent) => match fs::read_dir(root.join(parent)) {
                Ok(rd) => rd
                    .flatten()
                    .filter(|e| e.path().is_dir())
                    .map(|e| format!("{parent}/{}", e.file_name().to_string_lossy()))
                    .collect(),
                Err(_) => Vec::new(),
            },
            None => vec![member.to_string()],
        };
        for rel_path in rel_paths {
            let manifest = root.join(&rel_path).join("Cargo.toml");
            if let Some(raw) = package_name(&manifest) {
                // Derive the upstream import name (idempotent: strip a prior `nextjs_`).
                let import_name = raw.strip_prefix("nextjs_").unwrap_or(&raw).to_string();
                let package_name = format!("nextjs_{import_name}");
                let has_lib = root.join(&rel_path).join("src/lib.rs").exists();
                out.push(Member {
                    import_name,
                    package_name,
                    rel_path,
                    manifest,
                    has_lib,
                });
            }
        }
    }
    out.sort_by(|a, b| a.import_name.cmp(&b.import_name));
    out
}

fn package_name(manifest: &Path) -> Option<String> {
    let doc: DocumentMut = fs::read_to_string(manifest).ok()?.parse().ok()?;
    Some(doc.get("package")?.get("name")?.as_str()?.to_string())
}

/// Add `[workspace.package]` and `[workspace.dependencies]` (mapping each import name
/// to its published package) to the root manifest.
fn edit_root_manifest(root: &Path, members: &[Member], version: &str) {
    let path = root.join("Cargo.toml");
    let mut doc = read_doc(&path);

    let mut package = Table::new();
    package.insert("version", value(version));
    package.insert("edition", value(EDITION));
    package.insert("license", value(LICENSE));
    package.insert("description", value(DESCRIPTION));
    package.insert("repository", value(REPOSITORY));

    let mut dependencies = Table::new();
    for member in members {
        let mut dep = InlineTable::new();
        dep.insert("package", Value::from(member.package_name.as_str()));
        dep.insert("version", Value::from(version));
        dep.insert("path", Value::from(member.rel_path.as_str()));
        dep.fmt();
        dependencies.insert(&member.import_name, value(dep));
    }

    let workspace = doc["workspace"].as_table_mut().expect("[workspace] table");
    workspace.insert("package", Item::Table(package));
    workspace.insert("dependencies", Item::Table(dependencies));

    fs::write(&path, doc.to_string()).expect("write workspace Cargo.toml");
}

/// Crates reachable from `react_compiler` over internal `[dependencies]` /
/// `[build-dependencies]` — the set to publish — including `react_compiler` itself.
fn publish_closure(members: &[Member], internal: &BTreeSet<&str>) -> BTreeSet<String> {
    let mut adjacency: HashMap<String, Vec<String>> = HashMap::new();
    for member in members {
        let doc = read_doc(&member.manifest);
        let mut deps = Vec::new();
        for section in ["dependencies", "build-dependencies"] {
            if let Some(table) = doc.get(section).and_then(Item::as_table) {
                for (key, _) in table.iter() {
                    if internal.contains(key) {
                        deps.push(key.to_string());
                    }
                }
            }
        }
        adjacency.insert(member.import_name.clone(), deps);
    }

    let mut closure = BTreeSet::new();
    let mut queue = VecDeque::from(["nextjs_react_compiler".to_string()]);
    while let Some(name) = queue.pop_front() {
        if !closure.insert(name.clone()) {
            continue;
        }
        if let Some(deps) = adjacency.get(&name) {
            queue.extend(deps.iter().cloned());
        }
    }
    closure
}

/// Rename the published `[package] name`, keep the `[lib] name`, inherit publishing
/// fields, set `publish`, and point internal deps at the workspace.
fn edit_member_manifest(member: &Member, internal: &BTreeSet<&str>, publish: bool) {
    let mut doc = read_doc(&member.manifest);

    if let Some(pkg) = doc.get_mut("package").and_then(Item::as_table_mut) {
        pkg.insert("name", value(member.package_name.as_str()));
        for field in ["version", "edition", "license", "description", "repository"] {
            pkg.insert(field, workspace_inherited());
        }
        // Insert `publish` after the inherited fields so the field order is identical
        // whether the manifest came fresh from upstream or was already transformed
        // (keeps `just sync` idempotent).
        pkg.insert("publish", value(publish));
    }

    // Keep the importable crate name as upstream so source needs no changes.
    if member.has_lib {
        if doc.get("lib").and_then(Item::as_table).is_none() {
            doc["lib"] = Item::Table(Table::new());
        }
        if let Some(lib) = doc["lib"].as_table_mut() {
            lib.insert("name", value(member.import_name.as_str()));
        }
    }

    for section in ["dependencies", "dev-dependencies", "build-dependencies"] {
        let keys: Vec<String> = match doc.get(section).and_then(Item::as_table) {
            Some(table) => table
                .iter()
                .map(|(k, _)| k.to_string())
                .filter(|k| internal.contains(k.as_str()))
                .collect(),
            None => continue,
        };
        for key in keys {
            let dep = workspace_dep(&doc[section][key.as_str()]);
            if let Some(table) = doc[section].as_table_mut() {
                table.insert(&key, dep);
            }
        }
    }

    swap_regex_lite(&mut doc);

    fs::write(&member.manifest, doc.to_string()).expect("write manifest");
}

/// Replace the `regex` dependency with a `regex-lite` package rename, keeping the
/// import name `regex` so upstream's `use regex::Regex;` needs no change. The
/// compiler only uses a simple anchored pattern (`captures`/`get`), all of which
/// `regex-lite` supports — and it pulls in far less than full `regex`. Idempotent.
fn swap_regex_lite(doc: &mut DocumentMut) {
    for section in ["dependencies", "dev-dependencies", "build-dependencies"] {
        let Some(table) = doc.get_mut(section).and_then(Item::as_table_mut) else {
            continue;
        };
        if !table.contains_key("regex") {
            continue;
        }
        let mut dep = InlineTable::new();
        dep.insert("package", Value::from("regex-lite"));
        dep.insert("version", Value::from("0.1"));
        table.insert("regex", value(dep));
    }
}

/// A dotted `field.workspace = true` item.
fn workspace_inherited() -> Item {
    let mut table = Table::new();
    table.set_dotted(true);
    table.insert("workspace", value(true));
    Item::Table(table)
}

/// `{ workspace = true }`, preserving `features` / `optional` / `default-features`.
fn workspace_dep(old: &Item) -> Item {
    let mut dep = InlineTable::new();
    dep.insert("workspace", Value::from(true));
    for key in ["features", "optional", "default-features"] {
        let existing = old
            .as_inline_table()
            .and_then(|t| t.get(key).cloned())
            .or_else(|| {
                old.as_table()
                    .and_then(|t| t.get(key))
                    .and_then(Item::as_value)
                    .cloned()
            });
        if let Some(v) = existing {
            dep.insert(key, v);
        }
    }
    dep.fmt();
    value(dep)
}

fn read_doc(path: &Path) -> DocumentMut {
    fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
        .parse()
        .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}
