[package]
name = "nextjs_react_compiler_lowering"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = true

[dependencies]
react_compiler_ast = { workspace = true }
react_compiler_hir = { workspace = true }
react_compiler_diagnostics = { workspace = true }
indexmap = "2"
serde_json = "1"

[lib]
name = "react_compiler_lowering"
