[package]
description.workspace = true
documentation = "https://rustdoc.swc.rs/swc_ecma_react_compiler/"
edition.workspace = true
license.workspace = true
name = "nextjs_react_compiler_swc"
repository.workspace = true
version.workspace = true
publish = false


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
indexmap           = { version = "2", features = ["serde"] }
react_compiler = { workspace = true }
react_compiler_ast = { workspace = true }
react_compiler_hir = { workspace = true }
rustc-hash         = "2"
serde              = { version = "1", features = ["derive"] }
serde_json         = "1"
swc_atoms          = "9"
swc_common         = "21"
swc_ecma_ast       = "23"
swc_ecma_codegen   = "26"
swc_ecma_parser    = "39"
swc_ecma_visit     = "23"

[lib]
name = "react_compiler_swc"

