[package]
name = "nextjs_react_compiler_inference"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = true

[dependencies]
react_compiler_hir = { workspace = true }
react_compiler_diagnostics = { workspace = true }
react_compiler_lowering = { workspace = true }
react_compiler_optimization = { workspace = true }
react_compiler_ssa = { workspace = true }
react_compiler_utils = { workspace = true }
indexmap = "2"

[lib]
name = "react_compiler_inference"
