[package]
name = "nextjs_react_compiler_validation"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = true

[dependencies]
indexmap = "2"
react_compiler_diagnostics = { workspace = true }
react_compiler_hir = { workspace = true }

[lib]
name = "react_compiler_validation"
